platform :ios,'8.0'
use_frameworks!
# for development https://github.com/CocoaPods/CocoaPods/pull/5254
install! 'cocoapods',
  :share_schemes_for_development_pods => true

target 'TYPinLock_Example' do
  pod 'TYPinLock', :path => '../'
  target 'TYPinLock_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
